export const techStack = [
  "Next.js",
  "React",
  "TypeScript",
  "GraphQL",
  "TanStack Query",
  "Redux Toolkit",
  "Node.js",
  "Express.js",
  "Websockets",
  "ORMs - Prisma, Mongoose",
  "PostgreSQL",
  "Redis",
  "Docker",
  "AWS",
  "Nginx",
];
